# Generated by Django 5.1.2 on 2024-10-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='devfest_participant',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
