# Generated by Django 5.1.2 on 2024-10-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_devfest_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(choices=[('facebook', 'facebook'), ('google', 'google'), ('twitter', 'twitter'), ('email', 'email')], default='email', max_length=255),
        ),
    ]
