# Generated by Django 5.1.2 on 2024-10-30 12:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_event_options_remove_event_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date', 'time']},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='location',
            new_name='venue',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_datetime',
        ),
        migrations.AddField(
            model_name='event',
            name='charge',
            field=models.CharField(choices=[('free', 'Free'), ('pay', 'Pay')], default='free', max_length=4),
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
